<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ws-16393" failures="1" tests="4" name="com.netcracker.shaw.ReinstateCases" time="25.672" errors="0" timestamp="2023-01-24T15:28:44 IST" skipped="3">
  <testcase classname="com.netcracker.shaw.ReinstateCases" name="Resinstate_Triple_Play_During_PremiseMove" time="25.672">
    <failure message="For input string: &quot;BK&quot; under radix 16 expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: For input string: "BK" under radix 16 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.netcracker.shaw.at_shaw_sd.pageobject.LandingPage.Login(LandingPage.java:69)
at com.netcracker.shaw.ReinstateCases.Resinstate_Triple_Play_During_PremiseMove(ReinstateCases.java:506)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Resinstate_Triple_Play_During_PremiseMove -->
  <system-out/>
  <testcase classname="com.netcracker.shaw.ReinstateCases" name="Disconnected_Resinstate_PastResource_CustOwned_Devices">
    <skipped/>
  </testcase> <!-- Disconnected_Resinstate_PastResource_CustOwned_Devices -->
  <system-out/>
  <testcase classname="com.netcracker.shaw.ReinstateCases" name="Fully_Disconnect_TriplePlay_Perform_Reinstate_New_Resources">
    <skipped/>
  </testcase> <!-- Fully_Disconnect_TriplePlay_Perform_Reinstate_New_Resources -->
  <system-out/>
  <testcase classname="com.netcracker.shaw.ReinstateCases" name="Booking_Service_Call_Reinstate_MOCA_Enabled_Hardware">
    <skipped/>
  </testcase> <!-- Booking_Service_Call_Reinstate_MOCA_Enabled_Hardware -->
  <system-out/>
</testsuite> <!-- com.netcracker.shaw.ReinstateCases -->
